### ISSUE TITLE
Issue with level exporter?

### ISSUE THREAD

**Issue by LinkestLink** [GoomiiV2/Rampancy#14]
Hi there! This tool is such a great idea, you're a genius! Anyways, I'm having an issue when I hit F6, it says 

NullReferenceException: Object reference not set to an instance of an object
Plugins.Rampancy.Runtime.LevelExporter+<>c__DisplayClass3_0.<GetRcsgMesh>b__0 (UnityEngine.GameObject x) (at Assets/Plugins/Rampancy/Runtime/LevelExporter.cs:47)
System.Linq.Enumerable+WhereArrayIterator`1[TSource].ToList () (at <b024aa277ab0422080e4a1dbe1f3c835>:0)
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <b024aa277ab0422080e4a1dbe1f3c835>:0)
Plugins.Rampancy.Runtime.LevelExporter.GetRcsgMesh () (at Assets/Plugins/Rampancy/Runtime/LevelExporter.cs:47)
Plugins.Rampancy.Runtime.LevelExporter.ExportLevel (System.String path, System.Boolean tJunctionFix) (at Assets/Plugins/Rampancy/Runtime/LevelExporter.cs:12)
Plugins.Rampancy.Runtime.Actions.ExportLevelJms (System.String jmsPath) (at Assets/Plugins/Rampancy/Runtime/Actions.cs:41)
Plugins.Rampancy.Runtime.Actions.H1_CompileStructure () (at Assets/Plugins/Rampancy/Runtime/Actions.Halo1Mcc.cs:20)
Plugins.Rampancy.Runtime.UI.LevelUI.CompileStructureAndPreviewLightmaps () (at Assets/Plugins/Rampancy/Runtime/UI/MainUI.cs:64)
UnityEditor.EditorApplication:Internal_CallGlobalEventHandler()

I'm not the best with Unity, sorry

**Comment by GoomiiV2** [comment]
Hey, thanks for test it out.

Can you try getting latest and see what the console log says?
I added more logging and error messages but from the sounds of it seems either the current scene you have open is empty or wasn't created from the Rampancy > Create New Level UI and so was missing some of the key game objects that creates.

I added a RampancySimple test scene under the examples/Halo1 you can try and see if that works?

**Comment by LinkestLink** [comment]
yeah the rampancy test works! you were right it turns out I forgot to do the Create New Level UI

**Comment by LinkestLink** [comment]
I'm also having an issue where everything is black in the level?

**Comment by GoomiiV2** [comment]
In tag test / Sapien you mean?
In that case you need to open the Scenario in Guerilla and add a sky and then rebuild it in Rampancy with f6, with out the sky there is no light source.
ATM Rampancy only replaces the Blender part of the level creation so you still need to setup the other parts in the mod tools like you would if using Blender.

I hope to make a quick start guide that goes more in depth on the setps needed to create a simple level with Rampancy soon.

**Comment by GoomiiV2** [comment]
I created a quick example of creating a new level here: https://github.com/GoomiiV2/Rampancy/wiki/Creating-a-new-level
