### ISSUE TITLE
Does not run when following instructions in README.md

### ISSUE THREAD

**Issue by Vaporeon** [GoomiiV2/Rampancy#15]
I followed the instructions in the readme and recursively cloned this repo as instructed.
When trying to open the project it errors complaining that some scripts fail to compile for the reasons shown in this image.

![image](https://user-images.githubusercontent.com/12814075/149611071-207d0429-deeb-4445-8d03-ab912c8502f5.png)

**Comment by GoomiiV2** [comment]
Ah sorry about that, I should have tested cloning it, issue seems to be from windows git not creating the symlink correctly.

Can you try recloning with ```git clone --recurse-submodules -c core.symlinks=true https://github.com/GoomiiV2/Rampancy.git``` from an admin command prompt.

I updated the readme and added a gitattributes to force it to be a directory symlink as that was another issue with it creating it as a file link

**Comment by Vaporeon** [comment]
Ah, thanks for the expatiation. I originally cloned it with Linux git but then Unity complained about not supporting case-sensitive directories, so I switched to windows git.

**Comment by GoomiiV2** [comment]
I want to put some time soon into the initial install and setup flow to streamline it.
Sadly part of the downsides of extending Unitys editor for this is, not being able to ship a nice self contained build and then having to deal with git for updates.

I forked Realtime csg now so hopefully I can convert it into a unity package so i won't need the submodule and symlink and that should atleast cut out the need for the elevated command prompt.
