### ISSUE TITLE
Error when trying to export basic box level

### ISSUE THREAD

**Issue by Pepper-Man** [GoomiiV2/Rampancy#18]
Hi, i'm probably being dumb but I have a very simple level with only like 7 brushes in it, but I had some open edges that I tried to fix, and whilst nothing is visually wrong I cannot get it to export anymore. Whenever I hit F6 I get this error and I have no idea what it means or how to fix it!

No idea if this is a me issue or not, the error is extremely vague lol

ArgumentException: An item with the same key has already been added. Key: Rampancy.WingedMesh+Edge
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <fd976842c3634855aba83404a44c7daa>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <fd976842c3634855aba83404a44c7daa>:0)
Rampancy.WingedMesh.FromUnityMesh (UnityEngine.Mesh mesh) (at Assets/Plugins/Rampancy/Runtime/WingedMesh.cs:61)
Rampancy.LevelExporter.FixTJunctionsV2 (UnityEngine.Mesh mesh) (at Assets/Plugins/Rampancy/Runtime/LevelExporter.cs:31)
Rampancy.LevelExporter.ExportLevel (System.String path, System.Boolean tJunctionFix) (at Assets/Plugins/Rampancy/Runtime/LevelExporter.cs:18)
Rampancy.Actions.ExportLevelJms (System.String jmsPath) (at Assets/Plugins/Rampancy/Runtime/Actions.cs:44)
Rampancy.Actions.H1_CompileStructure () (at Assets/Plugins/Rampancy/Runtime/Actions.Halo1Mcc.cs:19)
Rampancy.UI.LevelUI.CompileStructureAndPreviewLightmaps () (at Assets/Plugins/Rampancy/Runtime/UI/MainUI.cs:64)
UnityEditor.EditorApplication:Internal_CallGlobalEventHandler()

**Comment by GoomiiV2** [comment]
huh, can you send me the scene file that causes this so I can try and reproduce it?
